absl-py==0.13.0
addict==2.4.0
aiohttp==3.7.4.post0
antlr4-python3-runtime==4.8
appdirs==1.4.4
argon2-cffi==20.1.0
async-generator==1.10
async-timeout==3.0.1
attrs==21.2.0
backcall==0.2.0
black==21.4b2
bleach==3.3.0
cached-property==1.5.2
cachetools==4.2.2
catboost==0.26
certifi==2021.5.30
cffi==1.14.5
chardet==4.0.0
charset-normalizer==2.0.4
click==7.1.2
cloudpickle==1.6.0
colorama==0.4.4
cycler==0.10.0
Cython==0.29.28
decorator==5.0.9
defusedxml==0.7.1
detectron2==0.6+cu111
entrypoints==0.3
fsspec==2021.8.1
future==0.18.2
fuzzywuzzy==0.18.0
fvcore==0.1.5.post20220414
google-auth==1.35.0
google-auth-oauthlib==0.4.6
graphviz==0.16
grpcio==1.38.0
h5py==3.2.1
horovod==0.22.1
hydra-core==1.1.2
idna==3.2
imageio==2.18.0
imgaug==0.4.0
importlib-metadata==4.5.0
importlib-resources==5.2.3
iopath==0.1.9
ipykernel==5.5.5
ipympl==0.7.0
ipython==7.24.1
ipython-genutils==0.2.0
ipywidgets==7.6.3
jarowinkler==1.0.2
jedi==0.18.0
Jinja2==3.0.1
joblib==1.0.1
jsonschema==3.2.0
jupyter-client==6.2.0
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
kiwisolver==1.3.1
lanms-neo==1.0.2
lightgbm==3.2.1
llvmlite==0.38.0
lmdb==1.3.0
Markdown==3.3.4
MarkupSafe==2.0.1
matplotlib==3.4.2
matplotlib-inline==0.1.2
mistune==0.8.4
mmcv-full==1.6.0
mmdet==2.25.1
model-index==0.1.11
multidict==5.1.0
mypy-extensions==0.4.3
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.3
nest-asyncio==1.5.1
networkx==2.6.3
nltk==3.7
notebook==6.4.0
numba==0.55.1
numpy==1.20.3
oauthlib==3.1.1
omegaconf==2.1.2
opencv-python==4.5.2.54
opencv-python-headless==4.5.4.60
openmim==0.1.5
ordered-set==4.1.0
packaging==20.9
pandas==1.2.4
pandocfilters==1.4.3
parso==0.8.2
pathspec==0.9.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.1.0
plotly==4.14.3
portalocker==2.4.0
prometheus-client==0.11.0
prompt-toolkit==3.0.19
protobuf==3.17.3
psutil==5.8.0
ptyprocess==0.7.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyclipper==1.3.0.post2
pycocotools==2.0.2
pycparser==2.20
pyDeprecate==0.3.1
pydot==1.4.2
Pygments==2.9.0
PyMuPDF==1.20.1
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
pytorch-lightning==1.4.5
pytz==2021.1
PyWavelets==1.3.0
PyYAML==5.4.1
pyzmq==22.1.0
rapidfuzz==2.0.11
regex==2022.4.24
requests==2.26.0
requests-oauthlib==1.3.0
retrying==1.3.3
rsa==4.7.2
scikit-image==0.19.2
scikit-learn==0.24.2
scipy==1.7.0
seaborn==0.11.1
Send2Trash==1.5.0
Shapely==1.8.1.post1
six==1.16.0
sklearn==0.0
spyder-kernels==2.0.4
tabulate==0.8.9
tensorboard==2.6.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
termcolor==1.1.0
terminado==0.10.1
terminaltables==3.1.10
testpath==0.5.0
threadpoolctl==2.1.0
tifffile==2021.11.2
toml==0.10.2
torch==1.8.1+cu111
torchaudio==0.8.1
torchmetrics==0.5.1
torchvision==0.9.1+cu111
tornado==6.1
tqdm==4.62.2
traitlets==5.0.5
typed-ast==1.5.3
typing-extensions==3.10.0.0
urllib3==1.26.6
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==2.0.1
widgetsnbextension==3.5.1
wurlitzer==2.1.0
xgboost==1.4.2
yacs==0.1.8
yapf==0.32.0
yarl==1.6.3
zipp==3.4.1
